openapi: 3.0.0
info:
  title: Coffee API
  version: 1.0.5

paths:
  /categories/{slug}/products:
    get:
      summary: Get products by category slug
      tags: [Categories]
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of products in category
