openapi: 3.0.0
info:
  title: Coffee API
  version: 1.0.5

paths:
  /products:
    get:
      summary: Get all products
      tags: [Products]
      responses:
        "200":
          description: List of products
    post:
      summary: Create a new product
      tags: [Products]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photos:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        "201":
          description: Product created

  /products/{id}:
    get:
      summary: Get product by ID
      tags: [Products]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Product details
        "404":
          description: Product not found
    put:
      summary: Update product
      tags: [Products]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Product updated
    delete:
      summary: Delete product
      tags: [Products]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Product deleted

  /products/{id}/stock:
    patch:
      summary: Update product stock
      tags: [Products]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Stock updated
